### ISSUE TITLE
README rst doesn't seems to be properly parse by Pypi

### ISSUE THREAD

**Issue by scls19fr** [msabramo/setuptools-markdown#5]
Hello,

I'm trying to publish a Python package
https://pypi.python.org/pypi?:action=display&name=pandas_confusion&version=0.0.1

Code is available here
https://github.com/scls19fr/pandas_confusion

but README rst doesn't seems to be properly parsed by Pypi

Any idea ?

Kind regards

Sébastien

**Comment by msabramo** [comment]
Looks like your README.md just has a filename in it and no other text?

https://github.com/scls19fr/pandas_confusion/blob/master/README.md

**Comment by msabramo** [comment]
Oh oops I guess it's a symlink. Sorry I didn't realize GitHub showed symlinks that way.

**Comment by msabramo** [comment]
Often this is because of subtle errors in the markup that confuse PyPI. I've had good luck finding such errors with a tool called "restview". IIRC, it has a strict mode that flags some subtler errors.

**Comment by msabramo** [comment]
https://pypi.python.org/pypi/restview

**Comment by scls19fr** [comment]
Today is not my day ;-)

    Collecting restview
      Downloading restview-2.3.0.tar.gz
    Requirement already satisfied (use --upgrade to upgrade): docutils in /anaconda/lib/python2.7/site-packages (from restview)
    Collecting readme (from restview)
      Downloading readme-0.5.1-py2.py3-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): pygments in /anaconda/lib/python2.7/site-packages (from restview)
    Requirement already satisfied (use --upgrade to upgrade): six in /anaconda/lib/python2.7/site-packages (from readme->restview)
    Requirement already satisfied (use --upgrade to upgrade): bleach in /anaconda/lib/python2.7/site-packages (from readme->restview)
    Requirement already satisfied (use --upgrade to upgrade): html5lib>=0.999 in /anaconda/lib/python2.7/site-packages (from bleach->readme->restview)
    Installing collected packages: readme, restview
      Exception:
      Traceback (most recent call last):
        File "//anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
          status = self.run(options, args)
        File "//anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 352, in run
          root=options.root_path,
        File "//anaconda/lib/python2.7/site-packages/pip/req/req_set.py", line 693, in install
          **kwargs
        File "//anaconda/lib/python2.7/site-packages/pip/req/req_install.py", line 817, in install
          self.move_wheel_files(self.source_dir, root=root)
        File "//anaconda/lib/python2.7/site-packages/pip/req/req_install.py", line 1018, in move_wheel_files
          isolated=self.isolated,
        File "//anaconda/lib/python2.7/site-packages/pip/wheel.py", line 237, in move_wheel_files
          clobber(source, lib_dir, True)
        File "//anaconda/lib/python2.7/site-packages/pip/wheel.py", line 215, in clobber
          shutil.copyfile(srcfile, destfile)
        File "//anaconda/lib/python2.7/shutil.py", line 83, in copyfile
          with open(dst, 'wb') as fdst:
      IOError: [Errno 20] Not a directory: '//anaconda/lib/python2.7/site-packages/readme/__about__.py'

**Comment by scls19fr** [comment]
Where can I find the converted rst output file ?

**Comment by msabramo** [comment]
Haha yeah, not your day. :-) I think restview launches a GUI by default; can't remember if you can override that. 

You might want to file an issue at https://github.com/pypa/readme - that's the library PyPI is using to render the RST. And I think that and/or PyPI should give better messages to let you know why stuff isn't valid. You could also download that library and then try to make it render your code and do it in pdb perhaps.

**Comment by scls19fr** [comment]
I installed restview from source.

I output `README.rst` using:

    python setup.py --long-description > README.rst

Than I did

    restview --pypi-strict README.rst

It shows the following warning:

    README.rst:62: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.

Here is rst converted file:

    50: Matplotlib plot of a confusion matrix
    51: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    52:
    53: ::
    54: 
    55:     confusion_matrix.plot()
    56:     plt.show()
    57: 
    58: .. figure:: screenshots/cm.png
    59:    :alt: confusion\_matrix
    60: 
    61:    confusion\_matrix
    62: Matplotlib plot of a normalized confusion matrix
    63: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Markdown file was

    ### Matplotlib plot of a confusion matrix

        confusion_matrix.plot()
        plt.show()

    ![confusion_matrix](screenshots/cm.png)

    ### Matplotlib plot of a normalized confusion matrix

I noticed that if I manually add a blank line between line 61 and 62 it works but I can't do it because I need to change Markdown file... adding a blank line between cm.png and title "Matplotlib plot of a normalized confusion matrix" doesn't help.

Any idea ? An issue with Markdown -> RST converter ? ;-)

**Comment by scls19fr** [comment]
I also noticed that there is no reason for line 61 "confusion\_matrix" to be in rst file. I think the problem is with image with alt.

**Comment by scls19fr** [comment]
My problem is solved. Thanks.

**Comment by msabramo** [comment]
Glad you figured it out!

**Comment by scls19fr** [comment]
See http://bugs.python.org/issue24633
